---
apiVersion: v1
kind: Namespace
metadata:
  name: dev

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-sa
  namespace: "dev"
secrets: 
  - name: jenkins-secret

--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: "dev"
  name: jenkins-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "services", "serviceaccounts", "secrets"]
  verbs: ["get", "watch", "list", "create", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "get","list", "patch"]

--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-rb
  namespace: dev
subjects:
- kind: ServiceAccount
  name: jenkins-sa
  namespace: dev
roleRef:
  kind: Role 
  name: jenkins-role
  apiGroup: rbac.authorization.k8s.io 

--- 
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-secret
  namespace: dev
  annotations:
    kubernetes.io/service-account.name: jenkins-sa
type: kubernetes.io/service-account-token
